# DREPNet: Model Configuration
# For details on module implementation, please refer to the /modules directory.

backbone:
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128]] # 1-P2/4
  - [-1, 2, SEI, [256, False, 0.25]]
  - [-1, 1, Conv, [256]] # 3-P3/8
  - [-1, 2, SEI, [512, False, 0.25]]
  - [-1, 1, Conv, [512]] # 5-P4/16
  - [-1, 2, REE, [512, True]]
  - [-1, 1, Conv, [1024]] # 7-P5/32
  - [-1, 2, REE, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9
  - [-1, 2, PGA, [1024]] # 10

head:
  - [-1, 1, Conv, [512, 1, 1]] # 11
  - [6, 1, Conv, [512, 3, 2]] # 12-P5/32
  - [[-1, 11], 1, Concat, [1]]
  - [-1, 3, CSPStage, [512]] # 14

  - [-1, 1, DySample, [2, 'lp']] #15
  - [4, 1, Conv, [256, 3, 2]] # 16-P4/16
  - [[15, -1, 6], 1, Concat, [1]]
  - [-1, 3, CSPStage, [512]] # 18

  - [-1, 1, DySample, [2, 'lp']] # 19-P3/8
  - [2, 1, SPDConv, [256]] # 20 (P3/8-small)
  - [[-1, -2, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 1, CSPOmniKernel, []] # 22-P3/8
  - [-1, 3, CSPStage, [256]] # 23-P3/8

  - [-1, 1, SPDConv, [256]]#24
  - [[-1, 18], 1, Concat, [1]]#25
  - [-1, 3, CSPStage, [512]] # 26

  - [18, 1, SPDConv, [256]] # 27
  - [24, 1, SPDConv, [256]]
  - [[14, 27, -1], 1, Concat, [1]]
  - [-1, 3, CSPStage, [1024]] # 30

  - [[23, 26, 30], 1, Detect, [nc]]  # Detect(P3, P4, P5)

